{% set name = "fabio" %}
{% set version = "0.9.0" %}
{% set sha256 = "e8f357e24a7c128d9f9c01981de14fd092c9a4adf9896251402ca4d2fa382d1e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<36]
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
    # could use opencl, but need the package on conda-forge first
    # - opencl
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fabio
    - fabio.test
    - fabio.third_party

about:
  home: https://github.com/silx-kit/fabio
  license: GPL v3.0, GPL v2.0, MIT, GPL, LGPL v3.0, BSD 3-Clause, Apache 2.0
  license_file: copyright
  summary: I/O library for images produced by 2D X-ray detector
