{% set name = "fabio" %}
{% set version = "0.9.0" %}
{% set sha256 = "5f3971b7d8a22410eab6eedb5725271304708feaa54a0fcb941ea54d3aa394d9" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/silx-kit/{{ name }}/archive/v{{ version }}.tar.gz
  fn: fabio-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py<36]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - cython
    - numpy
    - pip
    # could use opencl, but need the package on conda-forge first
    # - opencl
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - fabio
    - fabio.test
    - fabio.third_party

about:
    home: https://github.com/silx-kit/fabio
    license: GPL v3.0, GPL v2.0, MIT, GPL, LGPL v3.0, BSD 3-Clause, Apache 2.0
    summary: I/O library for images produced by 2D X-ray detector
    license_family: Other
    license_file: copyright

extra:
    recipe-maintainers:
        - ericdill
        - licode
        - tacaswell
        - dmpelt
        - CJ-Wright
        - tschoonj
